/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.mobmonrob.vicon.datastreamapi.impl;

public class Client {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Client(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Client obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @Override
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ViconDataStreamClientSDKJNI.delete_Client(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Client() {
    this(ViconDataStreamClientSDKJNI.new_Client(), true);
  }

  public Output_GetVersion GetVersion() {
    return new Output_GetVersion(ViconDataStreamClientSDKJNI.Client_GetVersion(swigCPtr, this), true);
  }

  public Output_Connect Connect(CString HostName) {
    return new Output_Connect(ViconDataStreamClientSDKJNI.Client_Connect(swigCPtr, this, CString.getCPtr(HostName), HostName), true);
  }

  public Output_ConnectToMulticast ConnectToMulticast(CString LocalIP, CString MulticastIP) {
    return new Output_ConnectToMulticast(ViconDataStreamClientSDKJNI.Client_ConnectToMulticast(swigCPtr, this, CString.getCPtr(LocalIP), LocalIP, CString.getCPtr(MulticastIP), MulticastIP), true);
  }

  public Output_Disconnect Disconnect() {
    return new Output_Disconnect(ViconDataStreamClientSDKJNI.Client_Disconnect(swigCPtr, this), true);
  }

  public Output_IsConnected IsConnected() {
    return new Output_IsConnected(ViconDataStreamClientSDKJNI.Client_IsConnected(swigCPtr, this), true);
  }

  public Output_StartTransmittingMulticast StartTransmittingMulticast(CString ServerIP, CString MulticastIP) {
    return new Output_StartTransmittingMulticast(ViconDataStreamClientSDKJNI.Client_StartTransmittingMulticast(swigCPtr, this, CString.getCPtr(ServerIP), ServerIP, CString.getCPtr(MulticastIP), MulticastIP), true);
  }

  public Output_StopTransmittingMulticast StopTransmittingMulticast() {
    return new Output_StopTransmittingMulticast(ViconDataStreamClientSDKJNI.Client_StopTransmittingMulticast(swigCPtr, this), true);
  }

  public void SetBufferSize(long i_BufferSize) {
    ViconDataStreamClientSDKJNI.Client_SetBufferSize(swigCPtr, this, i_BufferSize);
  }

  public Output_EnableSegmentData EnableSegmentData() {
    return new Output_EnableSegmentData(ViconDataStreamClientSDKJNI.Client_EnableSegmentData(swigCPtr, this), true);
  }

  public Output_EnableMarkerData EnableMarkerData() {
    return new Output_EnableMarkerData(ViconDataStreamClientSDKJNI.Client_EnableMarkerData(swigCPtr, this), true);
  }

  public Output_EnableUnlabeledMarkerData EnableUnlabeledMarkerData() {
    return new Output_EnableUnlabeledMarkerData(ViconDataStreamClientSDKJNI.Client_EnableUnlabeledMarkerData(swigCPtr, this), true);
  }

  public Output_EnableMarkerRayData EnableMarkerRayData() {
    return new Output_EnableMarkerRayData(ViconDataStreamClientSDKJNI.Client_EnableMarkerRayData(swigCPtr, this), true);
  }

  public Output_EnableDeviceData EnableDeviceData() {
    return new Output_EnableDeviceData(ViconDataStreamClientSDKJNI.Client_EnableDeviceData(swigCPtr, this), true);
  }

  public Output_EnableCentroidData EnableCentroidData() {
    return new Output_EnableCentroidData(ViconDataStreamClientSDKJNI.Client_EnableCentroidData(swigCPtr, this), true);
  }

  public Output_EnableGreyscaleData EnableGreyscaleData() {
    return new Output_EnableGreyscaleData(ViconDataStreamClientSDKJNI.Client_EnableGreyscaleData(swigCPtr, this), true);
  }

  public Output_EnableDebugData EnableDebugData() {
    return new Output_EnableDebugData(ViconDataStreamClientSDKJNI.Client_EnableDebugData(swigCPtr, this), true);
  }

  public Output_DisableSegmentData DisableSegmentData() {
    return new Output_DisableSegmentData(ViconDataStreamClientSDKJNI.Client_DisableSegmentData(swigCPtr, this), true);
  }

  public Output_DisableMarkerData DisableMarkerData() {
    return new Output_DisableMarkerData(ViconDataStreamClientSDKJNI.Client_DisableMarkerData(swigCPtr, this), true);
  }

  public Output_DisableUnlabeledMarkerData DisableUnlabeledMarkerData() {
    return new Output_DisableUnlabeledMarkerData(ViconDataStreamClientSDKJNI.Client_DisableUnlabeledMarkerData(swigCPtr, this), true);
  }

  public Output_DisableMarkerRayData DisableMarkerRayData() {
    return new Output_DisableMarkerRayData(ViconDataStreamClientSDKJNI.Client_DisableMarkerRayData(swigCPtr, this), true);
  }

  public Output_DisableDeviceData DisableDeviceData() {
    return new Output_DisableDeviceData(ViconDataStreamClientSDKJNI.Client_DisableDeviceData(swigCPtr, this), true);
  }

  public Output_DisableCentroidData DisableCentroidData() {
    return new Output_DisableCentroidData(ViconDataStreamClientSDKJNI.Client_DisableCentroidData(swigCPtr, this), true);
  }

  public Output_DisableGreyscaleData DisableGreyscaleData() {
    return new Output_DisableGreyscaleData(ViconDataStreamClientSDKJNI.Client_DisableGreyscaleData(swigCPtr, this), true);
  }

  public Output_DisableDebugData DisableDebugData() {
    return new Output_DisableDebugData(ViconDataStreamClientSDKJNI.Client_DisableDebugData(swigCPtr, this), true);
  }

  public Output_IsSegmentDataEnabled IsSegmentDataEnabled() {
    return new Output_IsSegmentDataEnabled(ViconDataStreamClientSDKJNI.Client_IsSegmentDataEnabled(swigCPtr, this), true);
  }

  public Output_IsMarkerDataEnabled IsMarkerDataEnabled() {
    return new Output_IsMarkerDataEnabled(ViconDataStreamClientSDKJNI.Client_IsMarkerDataEnabled(swigCPtr, this), true);
  }

  public Output_IsUnlabeledMarkerDataEnabled IsUnlabeledMarkerDataEnabled() {
    return new Output_IsUnlabeledMarkerDataEnabled(ViconDataStreamClientSDKJNI.Client_IsUnlabeledMarkerDataEnabled(swigCPtr, this), true);
  }

  public Output_IsMarkerRayDataEnabled IsMarkerRayDataEnabled() {
    return new Output_IsMarkerRayDataEnabled(ViconDataStreamClientSDKJNI.Client_IsMarkerRayDataEnabled(swigCPtr, this), true);
  }

  public Output_IsDeviceDataEnabled IsDeviceDataEnabled() {
    return new Output_IsDeviceDataEnabled(ViconDataStreamClientSDKJNI.Client_IsDeviceDataEnabled(swigCPtr, this), true);
  }

  public Output_IsCentroidDataEnabled IsCentroidDataEnabled() {
    return new Output_IsCentroidDataEnabled(ViconDataStreamClientSDKJNI.Client_IsCentroidDataEnabled(swigCPtr, this), true);
  }

  public Output_IsGreyscaleDataEnabled IsGreyscaleDataEnabled() {
    return new Output_IsGreyscaleDataEnabled(ViconDataStreamClientSDKJNI.Client_IsGreyscaleDataEnabled(swigCPtr, this), true);
  }

  public Output_IsDebugDataEnabled IsDebugDataEnabled() {
    return new Output_IsDebugDataEnabled(ViconDataStreamClientSDKJNI.Client_IsDebugDataEnabled(swigCPtr, this), true);
  }

  public Output_SetApexDeviceFeedback SetApexDeviceFeedback(CString i_rDeviceName, boolean i_bOn) {
    return new Output_SetApexDeviceFeedback(ViconDataStreamClientSDKJNI.Client_SetApexDeviceFeedback(swigCPtr, this, CString.getCPtr(i_rDeviceName), i_rDeviceName, i_bOn), true);
  }

  public Output_GetAxisMapping GetAxisMapping() {
    return new Output_GetAxisMapping(ViconDataStreamClientSDKJNI.Client_GetAxisMapping(swigCPtr, this), true);
  }

  public Output_GetServerOrientation GetServerOrientation() {
    return new Output_GetServerOrientation(ViconDataStreamClientSDKJNI.Client_GetServerOrientation(swigCPtr, this), true);
  }

  public Output_GetFrame GetFrame() {
    return new Output_GetFrame(ViconDataStreamClientSDKJNI.Client_GetFrame(swigCPtr, this), true);
  }

  public Output_GetFrameNumber GetFrameNumber() {
    return new Output_GetFrameNumber(ViconDataStreamClientSDKJNI.Client_GetFrameNumber(swigCPtr, this), true);
  }

  public Output_GetTimecode GetTimecode() {
    return new Output_GetTimecode(ViconDataStreamClientSDKJNI.Client_GetTimecode(swigCPtr, this), true);
  }

  public Output_GetFrameRate GetFrameRate() {
    return new Output_GetFrameRate(ViconDataStreamClientSDKJNI.Client_GetFrameRate(swigCPtr, this), true);
  }

  public Output_GetLatencySampleCount GetLatencySampleCount() {
    return new Output_GetLatencySampleCount(ViconDataStreamClientSDKJNI.Client_GetLatencySampleCount(swigCPtr, this), true);
  }

  public Output_GetLatencySampleName GetLatencySampleName(long LatencySampleIndex) {
    return new Output_GetLatencySampleName(ViconDataStreamClientSDKJNI.Client_GetLatencySampleName(swigCPtr, this, LatencySampleIndex), true);
  }

  public Output_GetLatencySampleValue GetLatencySampleValue(CString LatencySampleName) {
    return new Output_GetLatencySampleValue(ViconDataStreamClientSDKJNI.Client_GetLatencySampleValue(swigCPtr, this, CString.getCPtr(LatencySampleName), LatencySampleName), true);
  }

  public Output_GetLatencyTotal GetLatencyTotal() {
    return new Output_GetLatencyTotal(ViconDataStreamClientSDKJNI.Client_GetLatencyTotal(swigCPtr, this), true);
  }

  public Output_GetHardwareFrameNumber GetHardwareFrameNumber() {
    return new Output_GetHardwareFrameNumber(ViconDataStreamClientSDKJNI.Client_GetHardwareFrameNumber(swigCPtr, this), true);
  }

  public Output_GetFrameRateCount GetFrameRateCount() {
    return new Output_GetFrameRateCount(ViconDataStreamClientSDKJNI.Client_GetFrameRateCount(swigCPtr, this), true);
  }

  public Output_GetFrameRateName GetFrameRateName(long FrameRateIndex) {
    return new Output_GetFrameRateName(ViconDataStreamClientSDKJNI.Client_GetFrameRateName(swigCPtr, this, FrameRateIndex), true);
  }

  public Output_GetFrameRateValue GetFrameRateValue(CString FrameRateName) {
    return new Output_GetFrameRateValue(ViconDataStreamClientSDKJNI.Client_GetFrameRateValue(swigCPtr, this, CString.getCPtr(FrameRateName), FrameRateName), true);
  }

  public Output_GetSubjectCount GetSubjectCount() {
    return new Output_GetSubjectCount(ViconDataStreamClientSDKJNI.Client_GetSubjectCount(swigCPtr, this), true);
  }

  public Output_GetSubjectName GetSubjectName(long SubjectIndex) {
    return new Output_GetSubjectName(ViconDataStreamClientSDKJNI.Client_GetSubjectName(swigCPtr, this, SubjectIndex), true);
  }

  public Output_GetSubjectRootSegmentName GetSubjectRootSegmentName(CString SubjectName) {
    return new Output_GetSubjectRootSegmentName(ViconDataStreamClientSDKJNI.Client_GetSubjectRootSegmentName(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName), true);
  }

  public Output_GetSegmentCount GetSegmentCount(CString SubjectName) {
    return new Output_GetSegmentCount(ViconDataStreamClientSDKJNI.Client_GetSegmentCount(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName), true);
  }

  public Output_GetSegmentName GetSegmentName(CString SubjectName, long SegmentIndex) {
    return new Output_GetSegmentName(ViconDataStreamClientSDKJNI.Client_GetSegmentName(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, SegmentIndex), true);
  }

  public Output_GetSegmentChildCount GetSegmentChildCount(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentChildCount(ViconDataStreamClientSDKJNI.Client_GetSegmentChildCount(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentChildName GetSegmentChildName(CString SubjectName, CString SegmentName, long SegmentIndex) {
    return new Output_GetSegmentChildName(ViconDataStreamClientSDKJNI.Client_GetSegmentChildName(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName, SegmentIndex), true);
  }

  public Output_GetSegmentParentName GetSegmentParentName(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentParentName(ViconDataStreamClientSDKJNI.Client_GetSegmentParentName(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentStaticTranslation GetSegmentStaticTranslation(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentStaticTranslation(ViconDataStreamClientSDKJNI.Client_GetSegmentStaticTranslation(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentStaticRotationHelical GetSegmentStaticRotationHelical(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentStaticRotationHelical(ViconDataStreamClientSDKJNI.Client_GetSegmentStaticRotationHelical(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentStaticRotationMatrix GetSegmentStaticRotationMatrix(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentStaticRotationMatrix(ViconDataStreamClientSDKJNI.Client_GetSegmentStaticRotationMatrix(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentStaticRotationQuaternion GetSegmentStaticRotationQuaternion(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentStaticRotationQuaternion(ViconDataStreamClientSDKJNI.Client_GetSegmentStaticRotationQuaternion(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentStaticRotationEulerXYZ GetSegmentStaticRotationEulerXYZ(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentStaticRotationEulerXYZ(ViconDataStreamClientSDKJNI.Client_GetSegmentStaticRotationEulerXYZ(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentGlobalTranslation GetSegmentGlobalTranslation(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentGlobalTranslation(ViconDataStreamClientSDKJNI.Client_GetSegmentGlobalTranslation(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentGlobalRotationHelical GetSegmentGlobalRotationHelical(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentGlobalRotationHelical(ViconDataStreamClientSDKJNI.Client_GetSegmentGlobalRotationHelical(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentGlobalRotationMatrix GetSegmentGlobalRotationMatrix(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentGlobalRotationMatrix(ViconDataStreamClientSDKJNI.Client_GetSegmentGlobalRotationMatrix(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentGlobalRotationQuaternion GetSegmentGlobalRotationQuaternion(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentGlobalRotationQuaternion(ViconDataStreamClientSDKJNI.Client_GetSegmentGlobalRotationQuaternion(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentGlobalRotationEulerXYZ GetSegmentGlobalRotationEulerXYZ(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentGlobalRotationEulerXYZ(ViconDataStreamClientSDKJNI.Client_GetSegmentGlobalRotationEulerXYZ(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentLocalTranslation GetSegmentLocalTranslation(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentLocalTranslation(ViconDataStreamClientSDKJNI.Client_GetSegmentLocalTranslation(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentLocalRotationHelical GetSegmentLocalRotationHelical(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentLocalRotationHelical(ViconDataStreamClientSDKJNI.Client_GetSegmentLocalRotationHelical(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentLocalRotationMatrix GetSegmentLocalRotationMatrix(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentLocalRotationMatrix(ViconDataStreamClientSDKJNI.Client_GetSegmentLocalRotationMatrix(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentLocalRotationQuaternion GetSegmentLocalRotationQuaternion(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentLocalRotationQuaternion(ViconDataStreamClientSDKJNI.Client_GetSegmentLocalRotationQuaternion(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetSegmentLocalRotationEulerXYZ GetSegmentLocalRotationEulerXYZ(CString SubjectName, CString SegmentName) {
    return new Output_GetSegmentLocalRotationEulerXYZ(ViconDataStreamClientSDKJNI.Client_GetSegmentLocalRotationEulerXYZ(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(SegmentName), SegmentName), true);
  }

  public Output_GetObjectQuality GetObjectQuality(CString ObjectName) {
    return new Output_GetObjectQuality(ViconDataStreamClientSDKJNI.Client_GetObjectQuality(swigCPtr, this, CString.getCPtr(ObjectName), ObjectName), true);
  }

  public Output_GetMarkerCount GetMarkerCount(CString SubjectName) {
    return new Output_GetMarkerCount(ViconDataStreamClientSDKJNI.Client_GetMarkerCount(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName), true);
  }

  public Output_GetMarkerName GetMarkerName(CString SubjectName, long MarkerIndex) {
    return new Output_GetMarkerName(ViconDataStreamClientSDKJNI.Client_GetMarkerName(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, MarkerIndex), true);
  }

  public Output_GetMarkerParentName GetMarkerParentName(CString SubjectName, CString MarkerName) {
    return new Output_GetMarkerParentName(ViconDataStreamClientSDKJNI.Client_GetMarkerParentName(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(MarkerName), MarkerName), true);
  }

  public Output_GetMarkerGlobalTranslation GetMarkerGlobalTranslation(CString SubjectName, CString MarkerName) {
    return new Output_GetMarkerGlobalTranslation(ViconDataStreamClientSDKJNI.Client_GetMarkerGlobalTranslation(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(MarkerName), MarkerName), true);
  }

  public Output_GetMarkerRayContributionCount GetMarkerRayContributionCount(CString SubjectName, CString MarkerName) {
    return new Output_GetMarkerRayContributionCount(ViconDataStreamClientSDKJNI.Client_GetMarkerRayContributionCount(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(MarkerName), MarkerName), true);
  }

  public Output_GetMarkerRayContribution GetMarkerRayContribution(CString SubjectName, CString MarkerName, long MarkerRayContributionIndex) {
    return new Output_GetMarkerRayContribution(ViconDataStreamClientSDKJNI.Client_GetMarkerRayContribution(swigCPtr, this, CString.getCPtr(SubjectName), SubjectName, CString.getCPtr(MarkerName), MarkerName, MarkerRayContributionIndex), true);
  }

  public Output_GetUnlabeledMarkerCount GetUnlabeledMarkerCount() {
    return new Output_GetUnlabeledMarkerCount(ViconDataStreamClientSDKJNI.Client_GetUnlabeledMarkerCount(swigCPtr, this), true);
  }

  public Output_GetUnlabeledMarkerGlobalTranslation GetUnlabeledMarkerGlobalTranslation(long MarkerIndex) {
    return new Output_GetUnlabeledMarkerGlobalTranslation(ViconDataStreamClientSDKJNI.Client_GetUnlabeledMarkerGlobalTranslation(swigCPtr, this, MarkerIndex), true);
  }

  public Output_GetLabeledMarkerCount GetLabeledMarkerCount() {
    return new Output_GetLabeledMarkerCount(ViconDataStreamClientSDKJNI.Client_GetLabeledMarkerCount(swigCPtr, this), true);
  }

  public Output_GetLabeledMarkerGlobalTranslation GetLabeledMarkerGlobalTranslation(long MarkerIndex) {
    return new Output_GetLabeledMarkerGlobalTranslation(ViconDataStreamClientSDKJNI.Client_GetLabeledMarkerGlobalTranslation(swigCPtr, this, MarkerIndex), true);
  }

  public Output_GetDeviceCount GetDeviceCount() {
    return new Output_GetDeviceCount(ViconDataStreamClientSDKJNI.Client_GetDeviceCount(swigCPtr, this), true);
  }

  public Output_GetDeviceName GetDeviceName(long DeviceIndex) {
    return new Output_GetDeviceName(ViconDataStreamClientSDKJNI.Client_GetDeviceName(swigCPtr, this, DeviceIndex), true);
  }

  public Output_GetDeviceOutputCount GetDeviceOutputCount(CString DeviceName) {
    return new Output_GetDeviceOutputCount(ViconDataStreamClientSDKJNI.Client_GetDeviceOutputCount(swigCPtr, this, CString.getCPtr(DeviceName), DeviceName), true);
  }

  public Output_GetDeviceOutputName GetDeviceOutputName(CString DeviceName, long DeviceOutputIndex) {
    return new Output_GetDeviceOutputName(ViconDataStreamClientSDKJNI.Client_GetDeviceOutputName(swigCPtr, this, CString.getCPtr(DeviceName), DeviceName, DeviceOutputIndex), true);
  }

  public Output_GetDeviceOutputValue GetDeviceOutputValue(CString DeviceName, CString DeviceOutputName) {
    return new Output_GetDeviceOutputValue(ViconDataStreamClientSDKJNI.Client_GetDeviceOutputValue__SWIG_0(swigCPtr, this, CString.getCPtr(DeviceName), DeviceName, CString.getCPtr(DeviceOutputName), DeviceOutputName), true);
  }

  public Output_GetDeviceOutputSubsamples GetDeviceOutputSubsamples(CString DeviceName, CString DeviceOutputName) {
    return new Output_GetDeviceOutputSubsamples(ViconDataStreamClientSDKJNI.Client_GetDeviceOutputSubsamples(swigCPtr, this, CString.getCPtr(DeviceName), DeviceName, CString.getCPtr(DeviceOutputName), DeviceOutputName), true);
  }

  public Output_GetDeviceOutputValue GetDeviceOutputValue(CString DeviceName, CString DeviceOutputName, long Subsample) {
    return new Output_GetDeviceOutputValue(ViconDataStreamClientSDKJNI.Client_GetDeviceOutputValue__SWIG_1(swigCPtr, this, CString.getCPtr(DeviceName), DeviceName, CString.getCPtr(DeviceOutputName), DeviceOutputName, Subsample), true);
  }

  public Output_GetForcePlateCount GetForcePlateCount() {
    return new Output_GetForcePlateCount(ViconDataStreamClientSDKJNI.Client_GetForcePlateCount(swigCPtr, this), true);
  }

  public Output_GetGlobalForceVector GetGlobalForceVector(long ForcePlateIndex) {
    return new Output_GetGlobalForceVector(ViconDataStreamClientSDKJNI.Client_GetGlobalForceVector__SWIG_0(swigCPtr, this, ForcePlateIndex), true);
  }

  public Output_GetGlobalMomentVector GetGlobalMomentVector(long ForcePlateIndex) {
    return new Output_GetGlobalMomentVector(ViconDataStreamClientSDKJNI.Client_GetGlobalMomentVector__SWIG_0(swigCPtr, this, ForcePlateIndex), true);
  }

  public Output_GetGlobalCentreOfPressure GetGlobalCentreOfPressure(long ForcePlateIndex) {
    return new Output_GetGlobalCentreOfPressure(ViconDataStreamClientSDKJNI.Client_GetGlobalCentreOfPressure__SWIG_0(swigCPtr, this, ForcePlateIndex), true);
  }

  public Output_GetForcePlateSubsamples GetForcePlateSubsamples(long ForcePlateIndex) {
    return new Output_GetForcePlateSubsamples(ViconDataStreamClientSDKJNI.Client_GetForcePlateSubsamples(swigCPtr, this, ForcePlateIndex), true);
  }

  public Output_GetGlobalForceVector GetGlobalForceVector(long ForcePlateIndex, long Subsample) {
    return new Output_GetGlobalForceVector(ViconDataStreamClientSDKJNI.Client_GetGlobalForceVector__SWIG_1(swigCPtr, this, ForcePlateIndex, Subsample), true);
  }

  public Output_GetGlobalMomentVector GetGlobalMomentVector(long ForcePlateIndex, long Subsample) {
    return new Output_GetGlobalMomentVector(ViconDataStreamClientSDKJNI.Client_GetGlobalMomentVector__SWIG_1(swigCPtr, this, ForcePlateIndex, Subsample), true);
  }

  public Output_GetGlobalCentreOfPressure GetGlobalCentreOfPressure(long ForcePlateIndex, long Subsample) {
    return new Output_GetGlobalCentreOfPressure(ViconDataStreamClientSDKJNI.Client_GetGlobalCentreOfPressure__SWIG_1(swigCPtr, this, ForcePlateIndex, Subsample), true);
  }

  public Output_GetEyeTrackerCount GetEyeTrackerCount() {
    return new Output_GetEyeTrackerCount(ViconDataStreamClientSDKJNI.Client_GetEyeTrackerCount(swigCPtr, this), true);
  }

  public Output_GetEyeTrackerGlobalPosition GetEyeTrackerGlobalPosition(long EyeTrackerIndex) {
    return new Output_GetEyeTrackerGlobalPosition(ViconDataStreamClientSDKJNI.Client_GetEyeTrackerGlobalPosition(swigCPtr, this, EyeTrackerIndex), true);
  }

  public Output_GetEyeTrackerGlobalGazeVector GetEyeTrackerGlobalGazeVector(long EyeTrackerIndex) {
    return new Output_GetEyeTrackerGlobalGazeVector(ViconDataStreamClientSDKJNI.Client_GetEyeTrackerGlobalGazeVector(swigCPtr, this, EyeTrackerIndex), true);
  }

  public Output_GetCameraCount GetCameraCount() {
    return new Output_GetCameraCount(ViconDataStreamClientSDKJNI.Client_GetCameraCount(swigCPtr, this), true);
  }

  public Output_GetCameraName GetCameraName(long i_CameraIndex) {
    return new Output_GetCameraName(ViconDataStreamClientSDKJNI.Client_GetCameraName(swigCPtr, this, i_CameraIndex), true);
  }

  public Output_GetCameraId GetCameraId(SWIGTYPE_p_std__string i_rCameraName) {
    return new Output_GetCameraId(ViconDataStreamClientSDKJNI.Client_GetCameraId(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(i_rCameraName)), true);
  }

  public Output_GetCameraUserId GetCameraUserId(SWIGTYPE_p_std__string i_rCameraName) {
    return new Output_GetCameraUserId(ViconDataStreamClientSDKJNI.Client_GetCameraUserId(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(i_rCameraName)), true);
  }

  public Output_GetCameraType GetCameraType(SWIGTYPE_p_std__string i_rCameraName) {
    return new Output_GetCameraType(ViconDataStreamClientSDKJNI.Client_GetCameraType(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(i_rCameraName)), true);
  }

  public Output_GetCameraDisplayName GetCameraDisplayName(SWIGTYPE_p_std__string i_rCameraName) {
    return new Output_GetCameraDisplayName(ViconDataStreamClientSDKJNI.Client_GetCameraDisplayName(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(i_rCameraName)), true);
  }

  public Output_GetCameraResolution GetCameraResolution(SWIGTYPE_p_std__string i_rCameraName) {
    return new Output_GetCameraResolution(ViconDataStreamClientSDKJNI.Client_GetCameraResolution(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(i_rCameraName)), true);
  }

  public Output_GetIsVideoCamera GetIsVideoCamera(SWIGTYPE_p_std__string i_rCameraName) {
    return new Output_GetIsVideoCamera(ViconDataStreamClientSDKJNI.Client_GetIsVideoCamera(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(i_rCameraName)), true);
  }

  public Output_GetCentroidCount GetCentroidCount(SWIGTYPE_p_std__string i_rCameraName) {
    return new Output_GetCentroidCount(ViconDataStreamClientSDKJNI.Client_GetCentroidCount(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(i_rCameraName)), true);
  }

  public Output_GetCentroidPosition GetCentroidPosition(SWIGTYPE_p_std__string i_rCameraName, long i_CentroidIndex) {
    return new Output_GetCentroidPosition(ViconDataStreamClientSDKJNI.Client_GetCentroidPosition(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(i_rCameraName), i_CentroidIndex), true);
  }

  public Output_GetCentroidWeight GetCentroidWeight(SWIGTYPE_p_std__string i_rCameraName, long i_CentroidIndex) {
    return new Output_GetCentroidWeight(ViconDataStreamClientSDKJNI.Client_GetCentroidWeight(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(i_rCameraName), i_CentroidIndex), true);
  }

  public Output_GetGreyscaleBlobCount GetGreyscaleBlobCount(SWIGTYPE_p_std__string i_rCameraName) {
    return new Output_GetGreyscaleBlobCount(ViconDataStreamClientSDKJNI.Client_GetGreyscaleBlobCount(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(i_rCameraName)), true);
  }

  public Output_GetGreyscaleBlob GetGreyscaleBlob(SWIGTYPE_p_std__string i_rCameraName, long i_BlobIndex) {
    return new Output_GetGreyscaleBlob(ViconDataStreamClientSDKJNI.Client_GetGreyscaleBlob(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(i_rCameraName), i_BlobIndex), true);
  }

  public Output_SetCameraFilter SetCameraFilter(SWIGTYPE_p_std__vectorT_unsigned_int_t i_rCameraIdsForCentroids, SWIGTYPE_p_std__vectorT_unsigned_int_t i_rCameraIdsForBlobs) {
    return new Output_SetCameraFilter(ViconDataStreamClientSDKJNI.Client_SetCameraFilter(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(i_rCameraIdsForCentroids), SWIGTYPE_p_std__vectorT_unsigned_int_t.getCPtr(i_rCameraIdsForBlobs)), true);
  }

}
