/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.mobmonrob.vicon.datastreamapi.impl;

public class CString {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ViconDataStreamClientSDKJNI.delete_CString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CString(String i_pString) {
    this(ViconDataStreamClientSDKJNI.new_CString__SWIG_0(i_pString), true);
  }

  public CString() {
    this(ViconDataStreamClientSDKJNI.new_CString__SWIG_1(), true);
  }

  public CString(SWIGTYPE_p_std__string i_rString) {
    this(ViconDataStreamClientSDKJNI.new_CString__SWIG_2(SWIGTYPE_p_std__string.getCPtr(i_rString)), true);
  }

  public CString(CString i_rString) {
    this(ViconDataStreamClientSDKJNI.new_CString__SWIG_3(CString.getCPtr(i_rString), i_rString), true);
  }

  public void Set(String i_pString, IStringFactory i_rStringFactory) {
    ViconDataStreamClientSDKJNI.CString_Set(swigCPtr, this, i_pString, IStringFactory.getCPtr(i_rStringFactory), i_rStringFactory);
  }

  public String toString() {
    return ViconDataStreamClientSDKJNI.CString_toString(swigCPtr, this);
  }

}
