/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.mobmonrob.vicon.datastreamapi.impl;

public final class DeviceType_Enum {
  public final static DeviceType_Enum DeviceType_Unknown = new DeviceType_Enum("DeviceType_Unknown");
  public final static DeviceType_Enum ForcePlate = new DeviceType_Enum("ForcePlate");
  public final static DeviceType_Enum EyeTracker = new DeviceType_Enum("EyeTracker");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DeviceType_Enum swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DeviceType_Enum.class + " with value " + swigValue);
  }

  private DeviceType_Enum(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DeviceType_Enum(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DeviceType_Enum(String swigName, DeviceType_Enum swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DeviceType_Enum[] swigValues = { DeviceType_Unknown, ForcePlate, EyeTracker };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

