/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.mobmonrob.vicon.datastreamapi.impl;

public final class Direction_Enum {
  public final static Direction_Enum Up = new Direction_Enum("Up");
  public final static Direction_Enum Down = new Direction_Enum("Down");
  public final static Direction_Enum Left = new Direction_Enum("Left");
  public final static Direction_Enum Right = new Direction_Enum("Right");
  public final static Direction_Enum Forward = new Direction_Enum("Forward");
  public final static Direction_Enum Backward = new Direction_Enum("Backward");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Direction_Enum swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Direction_Enum.class + " with value " + swigValue);
  }

  private Direction_Enum(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Direction_Enum(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Direction_Enum(String swigName, Direction_Enum swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Direction_Enum[] swigValues = { Up, Down, Left, Right, Forward, Backward };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

