/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.mobmonrob.vicon.datastreamapi.impl;

public class Output_IsConnected {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Output_IsConnected(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Output_IsConnected obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ViconDataStreamClientSDKJNI.delete_Output_IsConnected(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setConnected(boolean value) {
    ViconDataStreamClientSDKJNI.Output_IsConnected_Connected_set(swigCPtr, this, value);
  }

  public boolean getConnected() {
    return ViconDataStreamClientSDKJNI.Output_IsConnected_Connected_get(swigCPtr, this);
  }

  public Output_IsConnected() {
    this(ViconDataStreamClientSDKJNI.new_Output_IsConnected(), true);
  }

}
