/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.mobmonrob.vicon.datastreamapi.impl;

public class Output_GetTimecode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Output_GetTimecode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Output_GetTimecode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ViconDataStreamClientSDKJNI.delete_Output_GetTimecode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setResult(Result_Enum value) {
    ViconDataStreamClientSDKJNI.Output_GetTimecode_Result_set(swigCPtr, this, value.swigValue());
  }

  public Result_Enum getResult() {
    return Result_Enum.swigToEnum(ViconDataStreamClientSDKJNI.Output_GetTimecode_Result_get(swigCPtr, this));
  }

  public void setHours(long value) {
    ViconDataStreamClientSDKJNI.Output_GetTimecode_Hours_set(swigCPtr, this, value);
  }

  public long getHours() {
    return ViconDataStreamClientSDKJNI.Output_GetTimecode_Hours_get(swigCPtr, this);
  }

  public void setMinutes(long value) {
    ViconDataStreamClientSDKJNI.Output_GetTimecode_Minutes_set(swigCPtr, this, value);
  }

  public long getMinutes() {
    return ViconDataStreamClientSDKJNI.Output_GetTimecode_Minutes_get(swigCPtr, this);
  }

  public void setSeconds(long value) {
    ViconDataStreamClientSDKJNI.Output_GetTimecode_Seconds_set(swigCPtr, this, value);
  }

  public long getSeconds() {
    return ViconDataStreamClientSDKJNI.Output_GetTimecode_Seconds_get(swigCPtr, this);
  }

  public void setFrames(long value) {
    ViconDataStreamClientSDKJNI.Output_GetTimecode_Frames_set(swigCPtr, this, value);
  }

  public long getFrames() {
    return ViconDataStreamClientSDKJNI.Output_GetTimecode_Frames_get(swigCPtr, this);
  }

  public void setSubFrame(long value) {
    ViconDataStreamClientSDKJNI.Output_GetTimecode_SubFrame_set(swigCPtr, this, value);
  }

  public long getSubFrame() {
    return ViconDataStreamClientSDKJNI.Output_GetTimecode_SubFrame_get(swigCPtr, this);
  }

  public void setFieldFlag(boolean value) {
    ViconDataStreamClientSDKJNI.Output_GetTimecode_FieldFlag_set(swigCPtr, this, value);
  }

  public boolean getFieldFlag() {
    return ViconDataStreamClientSDKJNI.Output_GetTimecode_FieldFlag_get(swigCPtr, this);
  }

  public void setStandard(TimecodeStandard_Enum value) {
    ViconDataStreamClientSDKJNI.Output_GetTimecode_Standard_set(swigCPtr, this, value.swigValue());
  }

  public TimecodeStandard_Enum getStandard() {
    return TimecodeStandard_Enum.swigToEnum(ViconDataStreamClientSDKJNI.Output_GetTimecode_Standard_get(swigCPtr, this));
  }

  public void setSubFramesPerFrame(long value) {
    ViconDataStreamClientSDKJNI.Output_GetTimecode_SubFramesPerFrame_set(swigCPtr, this, value);
  }

  public long getSubFramesPerFrame() {
    return ViconDataStreamClientSDKJNI.Output_GetTimecode_SubFramesPerFrame_get(swigCPtr, this);
  }

  public void setUserBits(long value) {
    ViconDataStreamClientSDKJNI.Output_GetTimecode_UserBits_set(swigCPtr, this, value);
  }

  public long getUserBits() {
    return ViconDataStreamClientSDKJNI.Output_GetTimecode_UserBits_get(swigCPtr, this);
  }

  public Output_GetTimecode() {
    this(ViconDataStreamClientSDKJNI.new_Output_GetTimecode(), true);
  }

}
