/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.mobmonrob.vicon.datastreamapi.impl;

public class Output_GetCentroidPosition {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Output_GetCentroidPosition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Output_GetCentroidPosition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ViconDataStreamClientSDKJNI.delete_Output_GetCentroidPosition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setResult(Result_Enum value) {
    ViconDataStreamClientSDKJNI.Output_GetCentroidPosition_Result_set(swigCPtr, this, value.swigValue());
  }

  public Result_Enum getResult() {
    return Result_Enum.swigToEnum(ViconDataStreamClientSDKJNI.Output_GetCentroidPosition_Result_get(swigCPtr, this));
  }

  public void setCentroidPosition(double[] value) {
    ViconDataStreamClientSDKJNI.Output_GetCentroidPosition_CentroidPosition_set(swigCPtr, this, value);
  }

  public double[] getCentroidPosition() {
    return ViconDataStreamClientSDKJNI.Output_GetCentroidPosition_CentroidPosition_get(swigCPtr, this);
  }

  public void setRadius(double value) {
    ViconDataStreamClientSDKJNI.Output_GetCentroidPosition_Radius_set(swigCPtr, this, value);
  }

  public double getRadius() {
    return ViconDataStreamClientSDKJNI.Output_GetCentroidPosition_Radius_get(swigCPtr, this);
  }

  public Output_GetCentroidPosition() {
    this(ViconDataStreamClientSDKJNI.new_Output_GetCentroidPosition(), true);
  }

}
