/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.mobmonrob.vicon.datastreamapi.impl;

public final class ServerOrientation_Enum {
  public final static ServerOrientation_Enum Unknown = new ServerOrientation_Enum("Unknown");
  public final static ServerOrientation_Enum YUp = new ServerOrientation_Enum("YUp");
  public final static ServerOrientation_Enum ZUp = new ServerOrientation_Enum("ZUp");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ServerOrientation_Enum swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ServerOrientation_Enum.class + " with value " + swigValue);
  }

  private ServerOrientation_Enum(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ServerOrientation_Enum(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ServerOrientation_Enum(String swigName, ServerOrientation_Enum swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ServerOrientation_Enum[] swigValues = { Unknown, YUp, ZUp };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

