/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.mobmonrob.vicon.datastreamapi.impl;

public final class StreamMode_Enum {
  public final static StreamMode_Enum ClientPull = new StreamMode_Enum("ClientPull");
  public final static StreamMode_Enum ClientPullPreFetch = new StreamMode_Enum("ClientPullPreFetch");
  public final static StreamMode_Enum ServerPush = new StreamMode_Enum("ServerPush");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static StreamMode_Enum swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + StreamMode_Enum.class + " with value " + swigValue);
  }

  private StreamMode_Enum(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private StreamMode_Enum(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private StreamMode_Enum(String swigName, StreamMode_Enum swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static StreamMode_Enum[] swigValues = { ClientPull, ClientPullPreFetch, ServerPush };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

